version: '3.7'

services:
  web:
    stdin_open: true
    tty: true
    # image: "carwashapp:0.0.1"
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ".:/usr/src/app"
      - bundle:/bundle
      - /usr/src/app/tmp
    command: ["./bin/start_dev_server"]
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: db_password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  bundle:
