version: '3.7'

services:
  web:
    stdin_open: true
    tty: true
    build:
      context: .
      target: dev
    ports:
      - "3001:3000"
    command: "./bin/start_dev_server"
    volumes:
      - ".:/usr/src/app"
      - bundle:/bundle
      - /usr/src/app/tmp
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: db_password
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  bundle:
  db:
