version: '3.7'

services:
  web:
    stdin_open: true
    tty: true
    image: "mmmikem/car-wash-app:0.0.5"
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: db_password
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: