 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/wash_types", type: :request do
  # WashType. As you add validations to WashType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      WashType.create! valid_attributes
      get wash_types_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      wash_type = WashType.create! valid_attributes
      get wash_type_url(wash_type)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_wash_type_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      wash_type = WashType.create! valid_attributes
      get edit_wash_type_url(wash_type)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new WashType" do
        expect {
          post wash_types_url, params: { wash_type: valid_attributes }
        }.to change(WashType, :count).by(1)
      end

      it "redirects to the created wash_type" do
        post wash_types_url, params: { wash_type: valid_attributes }
        expect(response).to redirect_to(wash_type_url(WashType.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new WashType" do
        expect {
          post wash_types_url, params: { wash_type: invalid_attributes }
        }.to change(WashType, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post wash_types_url, params: { wash_type: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested wash_type" do
        wash_type = WashType.create! valid_attributes
        patch wash_type_url(wash_type), params: { wash_type: new_attributes }
        wash_type.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the wash_type" do
        wash_type = WashType.create! valid_attributes
        patch wash_type_url(wash_type), params: { wash_type: new_attributes }
        wash_type.reload
        expect(response).to redirect_to(wash_type_url(wash_type))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        wash_type = WashType.create! valid_attributes
        patch wash_type_url(wash_type), params: { wash_type: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested wash_type" do
      wash_type = WashType.create! valid_attributes
      expect {
        delete wash_type_url(wash_type)
      }.to change(WashType, :count).by(-1)
    end

    it "redirects to the wash_types list" do
      wash_type = WashType.create! valid_attributes
      delete wash_type_url(wash_type)
      expect(response).to redirect_to(wash_types_url)
    end
  end
end
