name: Deploy

on:
  push:
    branches:
      - master
      - staging

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v2
      - name: Deploy to staging
        id: staging-deploy
        if: github.ref == 'refs/heads/staging'
        run: make deploy
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Deploy to production
        id: production-deploy
        if: github.ref == 'refs/heads/master'
        run: make prod_deploy
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
